name: Get events
on:
  push:
    branches:
      - "**"
  # schedule:
  #   - cron: "0 0 * * 1,4"

jobs:
  get_events:
    name: Get events
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Save google service account credentials
        shell: bash
        env:
          GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
        run: 'echo "$GOOGLE_SERVICE_ACCOUNT_CREDENTIALS" > google_service_account_credentials.json'
      - id: python
        name: Get Python events
        uses: ./.github/actions/get-events-action
        with:
          crawler-name: "PythonCrawler"
      - id: pycon
        name: Get PyCon events
        uses: ./.github/actions/get-events-action
        with:
          crawler-name: "PyConCrawler"
      - id: pydata
        name: Get PyData events
        uses: ./.github/actions/get-events-action
        with:
          crawler-name: "PyDataCrawler"
      # - id: papercall
      #   name: Get Papercall events
      #   uses: ./.github/actions/get-events-action
      #   with:
      #     crawler-name: 'PapercallCrawler'
      # TODO: remove
      # - id: Italy
      #   name: Get Italy events
      #   uses: ./.github/actions/get-events-action
      #   with:
      #     crawler-name: "ItalyCrawler"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: Add latest events
          COMMIT_AUTHOR_EMAIL: vinayak-mehta@users.noreply.github.com
          COMMIT_AUTHOR_NAME: Vinayak Mehta
          PULL_REQUEST_TITLE: "[WIP] Add latest events"
          PULL_REQUEST_BODY: Here's the latest event list!
          PULL_REQUEST_ASSIGNEES: vinayak-mehta
          PULL_REQUEST_REVIEWERS: vinayak-mehta
          PULL_REQUEST_BRANCH: add-events
          BRANCH_SUFFIX: short-commit-hash
